### ISSUE TITLE
Related to cr_domain.data

### ISSUE THREAD

**Issue by QishengL** [lrank/Domain_Robust_Text_Representation#2]
The format is 
num1 sentence num2. 
eg: 2 many pics of overly built up women \( think fitness competitions \) not something the average women can aspire too and too me is nasty looking 3 the information that was in it is general information that anyone with common sense already know ! my advice to you avoid this magazine unless you like body building or like looking at body builders	3

What do num1 and num2 represent?
I am guessing the first number is the sentiment and the second number is domain? Am I right?

**Comment by lrank** [comment]
https://github.com/lrank/Domain_Robust_Text_Representation/blob/master/data_helpers.py#L79 recalls the three attributes. And your guess is right.
